/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  Error,
  EventSiteOut,
  GetApiV1EventsitePagedParams,
  PaginatedResponseSchemaEventSiteOut
} from '../../schemas'
import { customInstance } from '../../customInstance';
import type { ErrorType } from '../../customInstance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary Get Paged
 */
export const GetApiV1EventsitePaged = (
    params?: GetApiV1EventsitePagedParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseSchemaEventSiteOut>(
      {url: `/api/v1/event_site/paged`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetApiV1EventsitePagedQueryKey = (params?: GetApiV1EventsitePagedParams,) => {
    return [`/api/v1/event_site/paged`, ...(params ? [params]: [])] as const;
    }

    
export const getGetApiV1EventsitePagedQueryOptions = <TData = Awaited<ReturnType<typeof GetApiV1EventsitePaged>>, TError = ErrorType<unknown>>(params?: GetApiV1EventsitePagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof GetApiV1EventsitePaged>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1EventsitePagedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof GetApiV1EventsitePaged>>> = ({ signal }) => GetApiV1EventsitePaged(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof GetApiV1EventsitePaged>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1EventsitePagedQueryResult = NonNullable<Awaited<ReturnType<typeof GetApiV1EventsitePaged>>>
export type GetApiV1EventsitePagedQueryError = ErrorType<unknown>

/**
 * @summary Get Paged
 */
export const useGetApiV1EventsitePaged = <TData = Awaited<ReturnType<typeof GetApiV1EventsitePaged>>, TError = ErrorType<unknown>>(
 params?: GetApiV1EventsitePagedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof GetApiV1EventsitePaged>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiV1EventsitePagedQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get All
 */
export const GetApiV1Eventsite = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EventSiteOut[]>(
      {url: `/api/v1/event_site`, method: 'GET', signal
    },
      options);
    }
  

export const getGetApiV1EventsiteQueryKey = () => {
    return [`/api/v1/event_site`] as const;
    }

    
export const getGetApiV1EventsiteQueryOptions = <TData = Awaited<ReturnType<typeof GetApiV1Eventsite>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof GetApiV1Eventsite>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1EventsiteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof GetApiV1Eventsite>>> = ({ signal }) => GetApiV1Eventsite(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof GetApiV1Eventsite>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1EventsiteQueryResult = NonNullable<Awaited<ReturnType<typeof GetApiV1Eventsite>>>
export type GetApiV1EventsiteQueryError = ErrorType<unknown>

/**
 * @summary Get All
 */
export const useGetApiV1Eventsite = <TData = Awaited<ReturnType<typeof GetApiV1Eventsite>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof GetApiV1Eventsite>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiV1EventsiteQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get By Id
 */
export const GetApiV1EventsiteId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EventSiteOut>(
      {url: `/api/v1/event_site/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetApiV1EventsiteIdQueryKey = (id: number,) => {
    return [`/api/v1/event_site/${id}`] as const;
    }

    
export const getGetApiV1EventsiteIdQueryOptions = <TData = Awaited<ReturnType<typeof GetApiV1EventsiteId>>, TError = ErrorType<Error>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof GetApiV1EventsiteId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1EventsiteIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof GetApiV1EventsiteId>>> = ({ signal }) => GetApiV1EventsiteId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof GetApiV1EventsiteId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1EventsiteIdQueryResult = NonNullable<Awaited<ReturnType<typeof GetApiV1EventsiteId>>>
export type GetApiV1EventsiteIdQueryError = ErrorType<Error>

/**
 * @summary Get By Id
 */
export const useGetApiV1EventsiteId = <TData = Awaited<ReturnType<typeof GetApiV1EventsiteId>>, TError = ErrorType<Error>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof GetApiV1EventsiteId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiV1EventsiteIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



