/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  Error,
  PromoIn,
  PromoValidationOut
} from '../../schemas'
import { customInstance } from '../../customInstance';
import type { ErrorType, BodyType } from '../../customInstance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary Validate
 */
export const PostApiV1PromoValidate = (
    promoIn: BodyType<PromoIn>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PromoValidationOut>(
      {url: `/api/v1/promo/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: promoIn
    },
      options);
    }
  


export const getPostApiV1PromoValidateMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof PostApiV1PromoValidate>>, TError,{data: BodyType<PromoIn>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof PostApiV1PromoValidate>>, TError,{data: BodyType<PromoIn>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof PostApiV1PromoValidate>>, {data: BodyType<PromoIn>}> = (props) => {
          const {data} = props ?? {};

          return  PostApiV1PromoValidate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PromoValidateMutationResult = NonNullable<Awaited<ReturnType<typeof PostApiV1PromoValidate>>>
    export type PostApiV1PromoValidateMutationBody = BodyType<PromoIn>
    export type PostApiV1PromoValidateMutationError = ErrorType<Error>

    /**
 * @summary Validate
 */
export const usePostApiV1PromoValidate = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof PostApiV1PromoValidate>>, TError,{data: BodyType<PromoIn>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof PostApiV1PromoValidate>>,
        TError,
        {data: BodyType<PromoIn>},
        TContext
      > => {

      const mutationOptions = getPostApiV1PromoValidateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    