/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventDetailsOut } from './eventDetailsOut';
import type { CartTicketOutId } from './cartTicketOutId';
import type { CartTicketOutOrder } from './cartTicketOutOrder';
import type { CartTicketOutSeat } from './cartTicketOutSeat';
import type { SectorWithoutRowsOut } from './sectorWithoutRowsOut';
import type { CartTicketOutSectorRow } from './cartTicketOutSectorRow';

export interface CartTicketOut {
  created_at: string;
  event: EventDetailsOut;
  format: string;
  id?: CartTicketOutId;
  is_printed: boolean;
  is_returned: boolean;
  is_scanned: boolean;
  order: CartTicketOutOrder;
  price: number;
  sale_price: number;
  seat?: CartTicketOutSeat;
  sector: SectorWithoutRowsOut;
  sector_row: CartTicketOutSectorRow;
  should_be_payed_at: string;
  status: string;
  type: string;
  unique_code: string;
}
