/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { CartOutId } from './cartOutId';
import type { CartTicketOut } from './cartTicketOut';

export interface CartOut {
  created_at: string;
  customer: number;
  id?: CartOutId;
  ticket: CartTicketOut;
}
