/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { CreateOneTicketInSeat } from './createOneTicketInSeat';
import type { CreateOneTicketInSectorId } from './createOneTicketInSectorId';
import type { CreateOneTicketInSectorRowId } from './createOneTicketInSectorRowId';

export interface CreateOneTicketIn {
  event_id: number;
  seat?: CreateOneTicketInSeat;
  sector_id?: CreateOneTicketInSectorId;
  sector_row_id?: CreateOneTicketInSectorRowId;
}
