/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { CustomerGenerateCodeOutDebugCode } from './customerGenerateCodeOutDebugCode';

export interface CustomerGenerateCodeOut {
  debug_code?: CustomerGenerateCodeOutDebugCode;
  status?: string;
  timer: number;
}
