/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { CustomerRegisterInCity } from './customerRegisterInCity';
import type { CustomerRegisterInCountry } from './customerRegisterInCountry';
import type { CustomerRegisterInEmail } from './customerRegisterInEmail';
import type { CustomerRegisterInSurname } from './customerRegisterInSurname';

export interface CustomerRegisterIn {
  city?: CustomerRegisterInCity;
  country?: CustomerRegisterInCountry;
  dob: string;
  email?: CustomerRegisterInEmail;
  /** @maxLength 12 */
  gender: string;
  /** @maxLength 64 */
  name: string;
  /** @maxLength 12 */
  phone: string;
  surname?: CustomerRegisterInSurname;
}
