/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { CustomerOutEmail } from './customerOutEmail';
import type { CustomerOutId } from './customerOutId';
import type { CustomerOutSurname } from './customerOutSurname';

export interface CustomerOut {
  /** @maxLength 64 */
  city: string;
  /** @maxLength 64 */
  country: string;
  dob: string;
  email?: CustomerOutEmail;
  email_is_activated?: boolean;
  /** @maxLength 12 */
  gender: string;
  id?: CustomerOutId;
  is_activated?: boolean;
  /** @maxLength 64 */
  name: string;
  /** @maxLength 12 */
  phone: string;
  surname?: CustomerOutSurname;
}
