/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: v1
 */

export interface CustomerRegister {
  /** @minLength 1 */
  readonly activation_code?: string;
  readonly activation_expires_at?: string;
  city?: string;
  country?: string;
  dob: string;
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /**
   * @minLength 1
   * @maxLength 12
   */
  gender: string;
  readonly id?: number;
  readonly is_activated?: boolean;
  /**
   * @minLength 1
   * @maxLength 32
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 12
   */
  phone: string;
}
