/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { CustomerUpdateProfileInSurname } from './customerUpdateProfileInSurname';

export interface CustomerUpdateProfileIn {
  /** @maxLength 64 */
  city: string;
  /** @maxLength 64 */
  country: string;
  dob: string;
  /** @maxLength 12 */
  gender: string;
  /** @maxLength 64 */
  name: string;
  surname?: CustomerUpdateProfileInSurname;
}
