/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: v1
 */

export interface CustomerRegisterResponse {
  /** @minLength 1 */
  access: string;
  /** @minLength 1 */
  refresh: string;
  /** @minLength 1 */
  status: string;
}
