/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: v1
 */

export interface CustomerActivate {
  /**
   * @minLength 1
   * @maxLength 6
   */
  activation_code: string;
  /**
   * @minLength 1
   * @maxLength 12
   */
  phone: string;
}
