/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */

export interface DirectorOut {
  created_at: string;
  first_name: string;
  id: number;
  last_name: string;
  login: string;
  middle_name: string;
  phone: string;
}
