/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventGroupMediaOut } from './eventGroupMediaOut';
import type { EventGroupToSponsorOut } from './eventGroupToSponsorOut';
import type { EventSiteOut } from './eventSiteOut';
import type { EventGroupOutId } from './eventGroupOutId';
import type { EventGroupOutSlug } from './eventGroupOutSlug';
import type { SubCategoryOut } from './subCategoryOut';

export interface EventGroupOut {
  description: string;
  description_en: string;
  description_ru: string;
  description_uz: string;
  event_group_medias: EventGroupMediaOut[];
  event_group_to_sponsors: EventGroupToSponsorOut[];
  event_site: EventSiteOut;
  finishes_at: string;
  hashtags: string[];
  hashtags_en: string[];
  hashtags_ru: string[];
  hashtags_uz: string[];
  id?: EventGroupOutId;
  is_favourite: boolean;
  minimal_age: number;
  name: string;
  name_en: string;
  name_ru: string;
  name_uz: string;
  slug?: EventGroupOutSlug;
  starts_at: string;
  sub_category: SubCategoryOut;
}
