/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventSiteOut } from './eventSiteOut';
import type { EventSiteSchemeOut2Id } from './eventSiteSchemeOut2Id';
import type { EventSiteSchemeOut2Svg } from './eventSiteSchemeOut2Svg';
import type { EventSiteSchemeOut2SvgMeta } from './eventSiteSchemeOut2SvgMeta';

export interface EventSiteSchemeOut2 {
  event_site: EventSiteOut;
  id?: EventSiteSchemeOut2Id;
  name: string;
  name_en: string;
  name_ru: string;
  name_uz: string;
  svg?: EventSiteSchemeOut2Svg;
  svg_meta?: EventSiteSchemeOut2SvgMeta;
}
