/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventSiteOutId } from './eventSiteOutId';
import type { EventSiteOutSlug } from './eventSiteOutSlug';

export interface EventSiteOut {
  address: string;
  /** @maxLength 64 */
  city: string;
  created_at: string;
  description: string;
  description_en: string;
  description_ru: string;
  description_uz: string;
  id?: EventSiteOutId;
  lat: string;
  long: string;
  name: string;
  name_en: string;
  name_ru: string;
  name_uz: string;
  /** @maxLength 12 */
  phone: string;
  photo: string;
  slug?: EventSiteOutSlug;
}
