/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventPriceRuleOutId } from './eventPriceRuleOutId';
import type { EventPriceRuleOutSeat } from './eventPriceRuleOutSeat';
import type { EventPriceRuleOutSector } from './eventPriceRuleOutSector';
import type { EventPriceRuleOutSectorRow } from './eventPriceRuleOutSectorRow';

export interface EventPriceRuleOut {
  destination: string;
  event: number;
  id?: EventPriceRuleOutId;
  price: number;
  seat?: EventPriceRuleOutSeat;
  sector?: EventPriceRuleOutSector;
  sector_row?: EventPriceRuleOutSectorRow;
}
