/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventPriceRuleInSeat } from './eventPriceRuleInSeat';

export interface EventPriceRuleIn {
  destination: string;
  event_id: number;
  price: number;
  seat?: EventPriceRuleInSeat;
  sector_id: number;
  sector_row_id: number;
}
