/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventSiteSchemeOutId } from './eventSiteSchemeOutId';
import type { EventSiteSchemeOutSvg } from './eventSiteSchemeOutSvg';
import type { EventSiteSchemeOutSvgMeta } from './eventSiteSchemeOutSvgMeta';

export interface EventSiteSchemeOut {
  event_site: number;
  id?: EventSiteSchemeOutId;
  name: string;
  name_en: string;
  name_ru: string;
  name_uz: string;
  svg?: EventSiteSchemeOutSvg;
  svg_meta?: EventSiteSchemeOutSvgMeta;
}
