/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventGroupOut } from './eventGroupOut';
import type { EventSiteSchemeOut2 } from './eventSiteSchemeOut2';
import type { EventDetailsOutId } from './eventDetailsOutId';

export interface EventDetailsOut {
  created_at: string;
  event_group: EventGroupOut;
  event_site_scheme: EventSiteSchemeOut2;
  finished_at: string;
  id?: EventDetailsOutId;
  name: string;
  name_en: string;
  name_ru: string;
  name_uz: string;
  started_at: string;
  status: string;
  ticket_refound_expires_at?: string;
  ticket_type: string;
  timer: number;
}
