/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */

export interface EventSiteIn {
  address: string;
  /** @maxLength 64 */
  city: string;
  coordinates: string;
  description: string;
  name: string;
  /** @maxLength 12 */
  phone: string;
  /** @maxLength 255 */
  photo: string;
  /** @maxLength 255 */
  slug: string;
}
