/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventGroupMediaOutId } from './eventGroupMediaOutId';

export interface EventGroupMediaOut {
  event_group: number;
  file: string;
  id?: EventGroupMediaOutId;
  media_type: string;
  priority: number;
}
