/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventGroupToSponsorOutId } from './eventGroupToSponsorOutId';
import type { SponsorOut } from './sponsorOut';

export interface EventGroupToSponsorOut {
  event_group: number;
  id?: EventGroupToSponsorOutId;
  sponsor: SponsorOut;
}
