/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventSectorRowSoldPlacesOut } from './eventSectorRowSoldPlacesOut';

export interface EventSectorSoldPlacesOut {
  id: number;
  sector_rows: EventSectorRowSoldPlacesOut[];
  sold_places_count: number;
}
