/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */

export interface EventDatesInfoOut {
  first_date: string;
  has_first_date: boolean;
  has_last_date: boolean;
  last_date: string;
}
