/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */

export interface EventIn {
  created_at: string;
  event_group_id_id: number;
  event_site_scheme_id_id: number;
  finished_at: string;
  is_deleted: boolean;
  started_at: string;
  status: number;
  ticket_refound_expires_at?: string;
  ticket_type: number;
  timer: number;
}
