/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventSiteSchemeInSvg } from './eventSiteSchemeInSvg';
import type { EventSiteSchemeInSvgMeta } from './eventSiteSchemeInSvgMeta';

export interface EventSiteSchemeIn {
  event_site_id: number;
  name_en: string;
  name_ru: string;
  name_uz: string;
  notes: string;
  svg?: EventSiteSchemeInSvg;
  svg_meta?: EventSiteSchemeInSvgMeta;
}
