/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */

export type GetApiV1EventRecommendedPagedParams = {
category?: number;
first_date?: string;
last_date?: string;
page?: number;
page_size?: number;
};
