/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventGroupOut } from './eventGroupOut';
import type { MainBannerOutId } from './mainBannerOutId';

export interface MainBannerOut {
  event_group: EventGroupOut;
  id?: MainBannerOutId;
  priority: number;
}
