/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { NewsOutId } from './newsOutId';

export interface NewsOut {
  created_at: string;
  id?: NewsOutId;
  photo: string;
  text: string;
  text_en: string;
  text_ru: string;
  text_uz: string;
  title: string;
  title_en: string;
  title_ru: string;
  title_uz: string;
}
