/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaMainBannerOutNext } from './paginatedResponseSchemaMainBannerOutNext';
import type { PaginatedResponseSchemaMainBannerOutPrevious } from './paginatedResponseSchemaMainBannerOutPrevious';
import type { MainBannerOut } from './mainBannerOut';

export interface PaginatedResponseSchemaMainBannerOut {
  count: number;
  next: PaginatedResponseSchemaMainBannerOutNext;
  previous: PaginatedResponseSchemaMainBannerOutPrevious;
  results: MainBannerOut[];
}
