/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaCategoryOutNext } from './paginatedResponseSchemaCategoryOutNext';
import type { PaginatedResponseSchemaCategoryOutPrevious } from './paginatedResponseSchemaCategoryOutPrevious';
import type { CategoryOut } from './categoryOut';

export interface PaginatedResponseSchemaCategoryOut {
  count: number;
  next: PaginatedResponseSchemaCategoryOutNext;
  previous: PaginatedResponseSchemaCategoryOutPrevious;
  results: CategoryOut[];
}
