/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaOrderOutNext } from './paginatedResponseSchemaOrderOutNext';
import type { PaginatedResponseSchemaOrderOutPrevious } from './paginatedResponseSchemaOrderOutPrevious';
import type { OrderOut } from './orderOut';

export interface PaginatedResponseSchemaOrderOut {
  count: number;
  next: PaginatedResponseSchemaOrderOutNext;
  previous: PaginatedResponseSchemaOrderOutPrevious;
  results: OrderOut[];
}
