/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaSectorOutNext } from './paginatedResponseSchemaSectorOutNext';
import type { PaginatedResponseSchemaSectorOutPrevious } from './paginatedResponseSchemaSectorOutPrevious';
import type { SectorOut } from './sectorOut';

export interface PaginatedResponseSchemaSectorOut {
  count: number;
  next: PaginatedResponseSchemaSectorOutNext;
  previous: PaginatedResponseSchemaSectorOutPrevious;
  results: SectorOut[];
}
