/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaEventGroupOutNext } from './paginatedResponseSchemaEventGroupOutNext';
import type { PaginatedResponseSchemaEventGroupOutPrevious } from './paginatedResponseSchemaEventGroupOutPrevious';
import type { EventGroupOut } from './eventGroupOut';

export interface PaginatedResponseSchemaEventGroupOut {
  count: number;
  next: PaginatedResponseSchemaEventGroupOutNext;
  previous: PaginatedResponseSchemaEventGroupOutPrevious;
  results: EventGroupOut[];
}
