/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaSponsorOutNext } from './paginatedResponseSchemaSponsorOutNext';
import type { PaginatedResponseSchemaSponsorOutPrevious } from './paginatedResponseSchemaSponsorOutPrevious';
import type { SponsorOut } from './sponsorOut';

export interface PaginatedResponseSchemaSponsorOut {
  count: number;
  next: PaginatedResponseSchemaSponsorOutNext;
  previous: PaginatedResponseSchemaSponsorOutPrevious;
  results: SponsorOut[];
}
