/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaEventSiteSchemeOutNext } from './paginatedResponseSchemaEventSiteSchemeOutNext';
import type { PaginatedResponseSchemaEventSiteSchemeOutPrevious } from './paginatedResponseSchemaEventSiteSchemeOutPrevious';
import type { EventSiteSchemeOut } from './eventSiteSchemeOut';

export interface PaginatedResponseSchemaEventSiteSchemeOut {
  count: number;
  next: PaginatedResponseSchemaEventSiteSchemeOutNext;
  previous: PaginatedResponseSchemaEventSiteSchemeOutPrevious;
  results: EventSiteSchemeOut[];
}
