/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaPointOfSaleOutNext } from './paginatedResponseSchemaPointOfSaleOutNext';
import type { PaginatedResponseSchemaPointOfSaleOutPrevious } from './paginatedResponseSchemaPointOfSaleOutPrevious';
import type { PointOfSaleOut } from './pointOfSaleOut';

export interface PaginatedResponseSchemaPointOfSaleOut {
  count: number;
  next: PaginatedResponseSchemaPointOfSaleOutNext;
  previous: PaginatedResponseSchemaPointOfSaleOutPrevious;
  results: PointOfSaleOut[];
}
