/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaEventSiteOutNext } from './paginatedResponseSchemaEventSiteOutNext';
import type { PaginatedResponseSchemaEventSiteOutPrevious } from './paginatedResponseSchemaEventSiteOutPrevious';
import type { EventSiteOut } from './eventSiteOut';

export interface PaginatedResponseSchemaEventSiteOut {
  count: number;
  next: PaginatedResponseSchemaEventSiteOutNext;
  previous: PaginatedResponseSchemaEventSiteOutPrevious;
  results: EventSiteOut[];
}
