/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaSectorRowOutNext } from './paginatedResponseSchemaSectorRowOutNext';
import type { PaginatedResponseSchemaSectorRowOutPrevious } from './paginatedResponseSchemaSectorRowOutPrevious';
import type { SectorRowOut } from './sectorRowOut';

export interface PaginatedResponseSchemaSectorRowOut {
  count: number;
  next: PaginatedResponseSchemaSectorRowOutNext;
  previous: PaginatedResponseSchemaSectorRowOutPrevious;
  results: SectorRowOut[];
}
