/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaSubCategoryOutNext } from './paginatedResponseSchemaSubCategoryOutNext';
import type { PaginatedResponseSchemaSubCategoryOutPrevious } from './paginatedResponseSchemaSubCategoryOutPrevious';
import type { SubCategoryOut } from './subCategoryOut';

export interface PaginatedResponseSchemaSubCategoryOut {
  count: number;
  next: PaginatedResponseSchemaSubCategoryOutNext;
  previous: PaginatedResponseSchemaSubCategoryOutPrevious;
  results: SubCategoryOut[];
}
