/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaPaymentMethodOutNext } from './paginatedResponseSchemaPaymentMethodOutNext';
import type { PaginatedResponseSchemaPaymentMethodOutPrevious } from './paginatedResponseSchemaPaymentMethodOutPrevious';
import type { PaymentMethodOut } from './paymentMethodOut';

export interface PaginatedResponseSchemaPaymentMethodOut {
  count: number;
  next: PaginatedResponseSchemaPaymentMethodOutNext;
  previous: PaginatedResponseSchemaPaymentMethodOutPrevious;
  results: PaymentMethodOut[];
}
