/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaEventDetailsOutNext } from './paginatedResponseSchemaEventDetailsOutNext';
import type { PaginatedResponseSchemaEventDetailsOutPrevious } from './paginatedResponseSchemaEventDetailsOutPrevious';
import type { EventDetailsOut } from './eventDetailsOut';

export interface PaginatedResponseSchemaEventDetailsOut {
  count: number;
  next: PaginatedResponseSchemaEventDetailsOutNext;
  previous: PaginatedResponseSchemaEventDetailsOutPrevious;
  results: EventDetailsOut[];
}
