/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseSchemaEventPriceRuleOutNext } from './paginatedResponseSchemaEventPriceRuleOutNext';
import type { PaginatedResponseSchemaEventPriceRuleOutPrevious } from './paginatedResponseSchemaEventPriceRuleOutPrevious';
import type { EventPriceRuleOut } from './eventPriceRuleOut';

export interface PaginatedResponseSchemaEventPriceRuleOut {
  count: number;
  next: PaginatedResponseSchemaEventPriceRuleOutNext;
  previous: PaginatedResponseSchemaEventPriceRuleOutPrevious;
  results: EventPriceRuleOut[];
}
