/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaymentOutId } from './paymentOutId';
import type { PaymentMethodOut } from './paymentMethodOut';

export interface PaymentOut {
  created_at: string;
  customer: number;
  id?: PaymentOutId;
  price: number;
  type: PaymentMethodOut;
}
