/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PaymentMethodOutId } from './paymentMethodOutId';

export interface PaymentMethodOut {
  icon: string;
  id?: PaymentMethodOutId;
  name: string;
  name_en: string;
  name_ru: string;
  name_uz: string;
}
