/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { PointOfSaleOutId } from './pointOfSaleOutId';

export interface PointOfSaleOut {
  address: string;
  id?: PointOfSaleOutId;
  lat: string;
  long: string;
  name_en: string;
  name_ru: string;
  name_uz: string;
  /** @maxLength 12 */
  phone: string;
  worktime_finishes_at: string;
  worktime_starts_at: string;
}
