/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { SeatOutId } from './seatOutId';

export interface SeatOut {
  column: number;
  id?: SeatOutId;
  name: string;
  sector_id: number;
}
