/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { SectorOutId } from './sectorOutId';
import type { SectorRowOut } from './sectorRowOut';

export interface SectorOut {
  capacity: number;
  event_site_scheme: number;
  has_rows: boolean;
  id?: SectorOutId;
  name: string;
  name_en: string;
  name_ru: string;
  name_uz: string;
  sector_rows: SectorRowOut[];
}
