/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { SectorRowOutId } from './sectorRowOutId';
import type { SectorRowOutSvg } from './sectorRowOutSvg';
import type { SectorRowOutSvgMeta } from './sectorRowOutSvgMeta';

export interface SectorRowOut {
  first_seat: number;
  id?: SectorRowOutId;
  last_seat: number;
  row: number;
  sector: number;
  svg?: SectorRowOutSvg;
  svg_meta?: SectorRowOutSvgMeta;
}
