/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { SectorRowInSvg } from './sectorRowInSvg';
import type { SectorRowInSvgMeta } from './sectorRowInSvgMeta';

export interface SectorRowIn {
  first_seat: number;
  last_seat: number;
  row: number;
  sector_id: number;
  svg?: SectorRowInSvg;
  svg_meta?: SectorRowInSvgMeta;
}
