/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { SectorDeleteOutId } from './sectorDeleteOutId';

export interface SectorDeleteOut {
  capacity: number;
  event_site_scheme: number;
  has_rows: boolean;
  id?: SectorDeleteOutId;
  name: string;
  name_en: string;
  name_ru: string;
  name_uz: string;
}
