/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { SponsorOutId } from './sponsorOutId';

export interface SponsorOut {
  icon: string;
  id?: SponsorOutId;
  name: string;
  name_en: string;
  name_ru: string;
  name_uz: string;
}
