/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import type { EventDetailsOut } from './eventDetailsOut';
import type { TicketOutId } from './ticketOutId';
import type { TicketOutOrder } from './ticketOutOrder';
import type { TicketOutSeat } from './ticketOutSeat';
import type { SectorWithoutRowsOut } from './sectorWithoutRowsOut';
import type { TicketOutSectorRow } from './ticketOutSectorRow';

export interface TicketOut {
  created_at: string;
  event: EventDetailsOut;
  format: string;
  id?: TicketOutId;
  is_printed: boolean;
  is_returned: boolean;
  is_scanned: boolean;
  order: TicketOutOrder;
  price: number;
  sale_price: number;
  seat?: TicketOutSeat;
  sector: SectorWithoutRowsOut;
  sector_row: TicketOutSectorRow;
  should_be_payed_at: string;
  status: string;
  type: string;
  unique_code: string;
}
