/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Probilet API
 * A simple instruction manual for those who need the probilet api.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  Error,
  FileUploadOut,
  PostApiV1FileUploadBody
} from '../../schemas'
import { customInstance } from '../../customInstance';
import type { ErrorType, BodyType } from '../../customInstance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary Upload
 */
export const PostApiV1FileUpload = (
    postApiV1FileUploadBody: BodyType<PostApiV1FileUploadBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      const formData = new FormData();
formData.append('file', postApiV1FileUploadBody.file)

      return customInstance<FileUploadOut>(
      {url: `/api/v1/file/upload`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getPostApiV1FileUploadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof PostApiV1FileUpload>>, TError,{data: BodyType<PostApiV1FileUploadBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof PostApiV1FileUpload>>, TError,{data: BodyType<PostApiV1FileUploadBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof PostApiV1FileUpload>>, {data: BodyType<PostApiV1FileUploadBody>}> = (props) => {
          const {data} = props ?? {};

          return  PostApiV1FileUpload(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1FileUploadMutationResult = NonNullable<Awaited<ReturnType<typeof PostApiV1FileUpload>>>
    export type PostApiV1FileUploadMutationBody = BodyType<PostApiV1FileUploadBody>
    export type PostApiV1FileUploadMutationError = ErrorType<unknown>

    /**
 * @summary Upload
 */
export const usePostApiV1FileUpload = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof PostApiV1FileUpload>>, TError,{data: BodyType<PostApiV1FileUploadBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof PostApiV1FileUpload>>,
        TError,
        {data: BodyType<PostApiV1FileUploadBody>},
        TContext
      > => {

      const mutationOptions = getPostApiV1FileUploadMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Download
 */
export const GetApiV1FileDownloadFileName = (
    fileName: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/file/download/${fileName}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetApiV1FileDownloadFileNameQueryKey = (fileName: string,) => {
    return [`/api/v1/file/download/${fileName}`] as const;
    }

    
export const getGetApiV1FileDownloadFileNameQueryOptions = <TData = Awaited<ReturnType<typeof GetApiV1FileDownloadFileName>>, TError = ErrorType<Error>>(fileName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof GetApiV1FileDownloadFileName>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1FileDownloadFileNameQueryKey(fileName);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof GetApiV1FileDownloadFileName>>> = ({ signal }) => GetApiV1FileDownloadFileName(fileName, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(fileName), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof GetApiV1FileDownloadFileName>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1FileDownloadFileNameQueryResult = NonNullable<Awaited<ReturnType<typeof GetApiV1FileDownloadFileName>>>
export type GetApiV1FileDownloadFileNameQueryError = ErrorType<Error>

/**
 * @summary Download
 */
export const useGetApiV1FileDownloadFileName = <TData = Awaited<ReturnType<typeof GetApiV1FileDownloadFileName>>, TError = ErrorType<Error>>(
 fileName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof GetApiV1FileDownloadFileName>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiV1FileDownloadFileNameQueryOptions(fileName,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



